package com.bluntsoftware.app.modules.dojomanager.repository;

import com.bluntsoftware.app.modules.dojomanager.domain.Dojo;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Dojo.
* @author autogenerated
*/

@Repository("dojomanagerDojoRepository")
@Qualifier("dojomanager")
//@RepositoryRestResource(collectionResourceRel="dojomanager.Dojo", path="dojomanager/Dojo")
public interface DojoRepository extends GenericRepository<Dojo,Integer>  {

}