package com.bluntsoftware.app.modules.dojomanager.repository;

import com.bluntsoftware.app.modules.dojomanager.domain.Student;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Student.
* @author autogenerated
*/

@Repository("dojomanagerStudentRepository")
@Qualifier("dojomanager")
//@RepositoryRestResource(collectionResourceRel="dojomanager.Student", path="dojomanager/Student")
public interface StudentRepository extends GenericRepository<Student,Integer>  {

}