package com.bluntsoftware.app.modules.dojomanager.repository;

import com.bluntsoftware.app.modules.dojomanager.domain.Studenttest;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Studenttest.
* @author autogenerated
*/

@Repository("dojomanagerStudenttestRepository")
@Qualifier("dojomanager")
//@RepositoryRestResource(collectionResourceRel="dojomanager.Studenttest", path="dojomanager/Studenttest")
public interface StudenttestRepository extends GenericRepository<Studenttest,Integer>  {

}